# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS_Viitor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS_Viitor

  target 'CS_ViitorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CS_ViitorUITests' do
    # Pods for testing
  end

pod 'FSCalendar'

end
